### PR TITLE
Accommodation

### PR DESCRIPTION
**Pull request by clovellbsc**
## Before you start

1. Have you run `git pull origin main` on your branch to bring in the latest changes?
2. Is there an issue on the repository for this request? If not, please create one.
3. Have you followed the correct workflow in the [team documentation](https://docs.google.com/document/d/13yi709ax4nmfTG9J0F57yEFpYRH7fdtczwvVJCrNIsM/edit#)?
4. Conflict resolution to be dealt with **on GitHub**.

## What do these code changes do?
Added full stack accommodation feature

## How do these code changes affect the application?
Can now access accommodation through the navbar
Accommodation can be added
Accommodation can be viewed in a formatted card

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] I have added thorough tests.
- [x] I have created a PR ticket on the [Trello board](https://trello.com/b/P8lEsvZe/acebook).
- [x] I will link the PR to the Trello card once created.
- [x] I will send the PR in the Slack channel and ping @here.

### CODE REVIEW

**Comment by heykathl** [comment]
[I would like to add details for my booked accommodation (modal)](https://trello.com/c/6njbj8zC/23-i-would-like-to-add-details-for-my-booked-accommodation-modal)

**Comment by heykathl** [comment]
[I would like to add details for my booked accommodation (view card)](https://trello.com/c/Aa2uIjOP/52-i-would-like-to-add-details-for-my-booked-accommodation-view-card)

**Review by adamwoodcock98 — APPROVED** [review]
Excellent work Chris!

**Comment by adamwoodcock98** [comment]
[Accommodation #37](https://trello.com/c/5Ysftg9q/57-accommodation-37)

**Review by heykathl — APPROVED** [review]
Amazing work Christopher!

**Pull request merged**
